# Generated by Django 5.0.4 on 2024-05-27 03:57

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('project', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='项目名称')),
                ('creat_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('log_file', models.FileField(upload_to=myapp.models.user_directory_path, verbose_name='log文件')),
                ('update_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[(0, '分析成功'), (1, '分析失败')], max_length=10)),
            ],
            options={
                'verbose_name': '2.分析结果',
                'verbose_name_plural': '2.分析结果',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('project', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='项目名称')),
                ('creat_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fastq_R1', models.FileField(upload_to=myapp.models.user_directory_path, verbose_name='R1 fastq')),
                ('fastq_R2', models.FileField(upload_to=myapp.models.user_directory_path, verbose_name='R2 fastq')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '1.数据分析',
                'verbose_name_plural': '1.数据分析',
            },
        ),
    ]
